refactor: shebang

diff --git a/gh/take-my-code b/gh/take-my-code
--- a/gh/take-my-code
+++ b/gh/take-my-code
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -e
 
@@ -10,22 +10,21 @@ set -e
 
 # EOF
 
-if [ -z "$1" ] ; then
-    echo -e "Usage: \e[0;31m ❌ take-my-code <branch-name>\e[0m"
-    exit 1
+if [ -z "$1" ]; then
+  echo -e "Usage: \e[0;31m ❌ take-my-code <branch-name>\e[0m"
+  exit 1
 fi
 
-eval "$(ssh-agent -s)" > /dev/null
+eval "$(ssh-agent -s)" >/dev/null
 OUTPUT=$(ssh-add ~/.ssh/github 2>&1)
 
 if [[ $OUTPUT =~ Identity\ added:\ .*\((.*)\) ]]; then
-    EMAIL=${BASH_REMATCH[1]}
-    echo -e "\e[1;32m ✔ Identity added for:\e[0m \e[1;33m$EMAIL\e[0m"
+  EMAIL=${BASH_REMATCH[1]}
+  echo -e "\e[1;32m ✔ Identity added for:\e[0m \e[1;33m$EMAIL\e[0m"
 else
-    echo -e "\e[1;31m✖ Failed to add identity\e[0m"
-    echo -e "\e[0;90m$OUTPUT\e[0m"
+  echo -e "\e[1;31m✖ Failed to add identity\e[0m"
+  echo -e "\e[0;90m$OUTPUT\e[0m"
 fi
-
 
 echo -e "\n\e[1;36m 📦 Git status:\e[0m"
 
@@ -36,12 +35,11 @@ PUSH_OUTPUT=$(git push origin "$1" 2>&1)
 
 echo -e "\n\e[1;36m$PUSH_OUTPUT\e[0m"
 
-
 echo -e "\e[1;32m ✔ Changes pushed successfully to \e[1;34morigin/$1\e[0m."
 
 repo=$(basename "$(git rev-parse --show-toplevel)")
 
 notify-send -u normal -a "GitHub" \
--h string:desktop-entry:github \
-"$repo: Push Successful" \
-"<i>Branch:</i> <span foreground='#61afef'>$1</span>\n<i>Remote:</i> <span foreground='#e5c07b'>origin/$1</span>"
+  -h string:desktop-entry:github \
+  "$repo: Push Successful" \
+  "<i>Branch:</i> <span foreground='#61afef'>$1</span>\n<i>Remote:</i> <span foreground='#e5c07b'>origin/$1</span>"
