fix: Improve script

diff --git a/fzf/git-diff b/fzf/git-diff
--- a/fzf/git-diff
+++ b/fzf/git-diff
@@ -2,22 +2,17 @@
 set -e
 
 BRANCH="$1"
+repo_root=$(git rev-parse --show-toplevel)
+
+list_changed_files() {
+  (
+    cd "$repo_root" || exit 1
+    git diff --name-only
+    git ls-files --other --exclude-standard
+  ) | sort -u
+}
 
 fzf_git() {
-
-  repo_root=$(git rev-parse --show-toplevel)
-  echo "$repo_root"
-
-  list_changed_files() {
-    (
-      cd "$repo_root" || exit 1
-      git diff --name-only
-      git ls-files --other --exclude-standard
-    ) | sort -u
-  }
-
-  any_file_staged=false
-
   staged_files=$(list_changed_files | fzf \
     --ansi \
     --style=full \
@@ -25,7 +20,7 @@ fzf_git() {
     --no-sort \
     --prompt='Stage > ' \
     --header-first \
-    --header='ENTER to stage selected files (CTRL-C to quit)' \
+    --header='ENTER to stage selected files (ESC to quit)' \
     --preview "git -C '$repo_root' diff --color=always -- {} | diff-so-fancy" \
     --bind 'enter:accept' \
     --border --padding=0,0 \
@@ -37,24 +32,15 @@ fzf_git() {
     --color 'header-border:#6699cc,header-label:#99ccff')
 
   if [[ -z "$staged_files" ]]; then
-    break
+    echo -e "\e[1;33mNo files selected. Exiting.\e[0m"
+    exit 0
   fi
 }
 
 do_commit() {
-
-  any_file_staged=true
-
   IFS=$'\n'
-
   set -- $staged_files
   git -C "$repo_root" add "$@"
-
-  # If nothing was staged, exit immediately
-  if [[ "$any_file_staged" == false ]]; then
-    echo -e "\e[1;33mNo files staged. Exiting.\e[0m"
-    exit 0
-  fi
 
   if [[ -z "$SSH_AUTH_SOCK" ]]; then
     eval "$(ssh-agent -s)" >/dev/null
@@ -62,7 +48,6 @@ do_commit() {
 }
 
 push() {
-
   OUTPUT=$(ssh-add ~/.ssh/github 2>&1)
   if [[ $OUTPUT =~ Identity\ added:\ .*\((.*)\) ]]; then
     EMAIL=${BASH_REMATCH[1]}
@@ -75,20 +60,16 @@ push() {
     exit 1
   fi
 
-  # Commit changes using template (editor opens automatically)
   git commit || {
     echo -e "\e[1;31m✖ Commit failed. Aborting push.\e[0m"
     exit 1
   }
 
-  # Push changes
   echo -e "\n\e[1;34m→ Pushing changes to origin/$BRANCH...\e[0m"
-  PUSH_OUTPUT=$(git push origin "$BRANCH" 2>&1)
-  if [[ $? -eq 0 ]]; then
+  if git push origin "$BRANCH"; then
     echo -e "\e[1;32m✔ Changes pushed successfully to \e[1;34morigin/$BRANCH\e[0m."
   else
-    echo -e "\e[1;31m✖ Push failed:\e[0m"
-    echo -e "\e[0;90m$PUSH_OUTPUT\e[0m"
+    echo -e "\e[1;31m✖ Push failed.\e[0m"
     exit 1
   fi
 }
